### ISSUE TITLE
is there a way to cache all results for OVA operations in the install-nsx-t job?

### ISSUE THREAD

**Issue by guillierf** [sparameswaran/nsx-t-gen#6]
All these steps take a long time (10 to 20 min in my lab) before deploying the OVA on vCenter:

calculate new NSX Manager OVF File Checksum
calculate new NSX Controller OVF File Checksum
calculate new NSX Gw OVF File Checksum
delete old checksum in .mf file
add new checksum in .mf file
delete old ova files
zip OVFs to OVAs using ovftool
remove OVF Folders with all Files

is it possible to cache the result?
reason is because if 1 parameter is modified in the nsx-t-parans.yml (like nsx manaer vm name for instance), we need to wait for a long time before getting the result of the operation.

thanks in advance

**Comment by sparameswaran** [comment]
Will check for some optimisation

- Sabha
-------- Original message --------From: Francis Guillier <notifications@github.com> Date: 5/6/18  10:29 AM  (GMT-08:00) To: sparameswaran/nsx-t-gen <nsx-t-gen@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [sparameswaran/nsx-t-gen] is there a way to cache all results for OVA
  operations in the install-nsx-t job? (#6) 
All these steps take a long time (10 to 20 min in my lab) before deploying the OVA on vCenter:
calculate new NSX Manager OVF File Checksum

calculate new NSX Controller OVF File Checksum

calculate new NSX Gw OVF File Checksum

delete old checksum in .mf file

add new checksum in .mf file

delete old ova files

zip OVFs to OVAs using ovftool

remove OVF Folders with all Files
is it possible to cache the result?

reason is because if 1 parameter is modified in the nsx-t-parans.yml (like nsx manaer vm name for instance), we need to wait for a long time before getting the result of the operation.
thanks in advance

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sparameswaran/nsx-t-gen","title":"sparameswaran/nsx-t-gen","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sparameswaran/nsx-t-gen"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"is there a way to cache all results for OVA operations in the install-nsx-t job? (#6)"}],"action":{"name":"View Issue","url":"https://github.com/sparameswaran/nsx-t-gen/issues/6"}}}

**Comment by guillierf** [comment]
make sure to have this parameter in the params file:
nsx_t_keep_reservation: true # for Prod setup

this will skip all the OVA operations
