### ISSUE TITLE
request to have a switch parameter in the param file: PKS or PAS or BOTH

### ISSUE THREAD

**Issue by guillierf** [sparameswaran/nsx-t-gen#9]
in case we just want to install NSX-T for PKS, some NSX-T objects are not necessary like the LB 
(in the default param file, there is this section which is not useful with PKS deployment:
nsx_t_lbr_spec: |
  loadbalancers:
  # Sample entry for creating
)

is it possible to have a switch parameter to specify the deployment:
PKS or PAS or BOTH

in case of PKS, step to create the LB is not activated for instance.

**Comment by sparameswaran** [comment]
Hi Francis,    The sample params is just showing what's possible. You can definitely remove or change the logical switches, t1 routers, lbrs
Just make sure the lbr spec value is set to be empty and then no lbr would be created.
nsx_t_lbr_spec: #empty now
-------- Original message --------From: Francis Guillier <notifications@github.com> Date: 5/18/18  3:44 PM  (GMT-08:00) To: sparameswaran/nsx-t-gen <nsx-t-gen@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [sparameswaran/nsx-t-gen] request to have a switch parameter in the
  param file: PKS or PAS or BOTH (#9) 
in case we just want to install NSX-T for PKS, some NSX-T objects are not necessary like the LB

(in the default param file, there is this section which is not useful with PKS deployment:

nsx_t_lbr_spec: |

loadbalancers:
Sample entry for creating
)
is it possible to have a switch parameter to specify the deployment:

PKS or PAS or BOTH
in case of PKS, step to create the LB is not activated for instance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/sparameswaran/nsx-t-gen/issues/9","url":"https://github.com/sparameswaran/nsx-t-gen/issues/9","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sparameswaran/nsx-t-gen","title":"sparameswaran/nsx-t-gen","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sparameswaran/nsx-t-gen"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"request to have a switch parameter in the param file: PKS or PAS or BOTH (#9)"}],"action":{"name":"View Issue","url":"https://github.com/sparameswaran/nsx-t-gen/issues/9"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "request to have a switch parameter in the param file: PKS or PAS or BOTH (#9)",
"sections": [
{
"text": "",
"activityTitle": "**Francis Guillier**",
"activityImage": "https://avatars1.githubusercontent.com/u/22355884?s=160\u0026v=4",
"activitySubtitle": "@guillierf",
"facts": [
{
"name": "Repository: ",
"value": "sparameswaran/nsx-t-gen"
},
{
"name": "Issue #: ",
"value": 9
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"sparameswaran/nsx-t-gen\",\n\"issueId\": 9,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"sparameswaran/nsx-t-gen\",\n\"issueId\": 9\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/sparameswaran/nsx-t-gen/issues/9"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 336971339\n}"
}
],
"themeColor": "26292E"
}

**Comment by guillierf** [comment]
hi Sabha

I tried to empty the nsx_t_lbr_spec section but the pipeline sends an error message when reaching that step and mentions that it cannot be empty.
If you want, I can replay the test and send you the output

**Comment by sparameswaran** [comment]
Thanks, will check and update.
-------- Original message --------From: Francis Guillier <notifications@github.com> Date: 5/18/18  7:46 PM  (GMT-08:00) To: sparameswaran/nsx-t-gen <nsx-t-gen@noreply.github.com> Cc: Sabha Parameswaran <sparameswaran@gopivotal.com>, Comment <comment@noreply.github.com> Subject: Re: [sparameswaran/nsx-t-gen] request to have a switch parameter in
  the param file: PKS or PAS or BOTH (#9) 
hi Sabha
I tried to empty the nsx_t_lbr_spec section but the pipeline sends an error message when reaching that step and mentions that it cannot be empty.

If you want, I can replay the test and send you the output

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/sparameswaran/nsx-t-gen/issues/9#issuecomment-390373044","url":"https://github.com/sparameswaran/nsx-t-gen/issues/9#issuecomment-390373044","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sparameswaran/nsx-t-gen","title":"sparameswaran/nsx-t-gen","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sparameswaran/nsx-t-gen"}},"updates":{"snippets":[{"icon":"PERSON","message":"@guillierf in #9: hi Sabha\r\n\r\nI tried to empty the nsx_t_lbr_spec section but the pipeline sends an error message when reaching that step and mentions that it cannot be empty.\r\nIf you want, I can replay the test and send you the output"}],"action":{"name":"View Issue","url":"https://github.com/sparameswaran/nsx-t-gen/issues/9#issuecomment-390373044"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [sparameswaran/nsx-t-gen] request to have a switch parameter in the param file: PKS or PAS or BOTH (#9)",
"sections": [
{
"text": "",
"activityTitle": "**Francis Guillier**",
"activityImage": "https://avatars1.githubusercontent.com/u/22355884?s=160\u0026v=4",
"activitySubtitle": "@guillierf",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"sparameswaran/nsx-t-gen\",\n\"issueId\": 9,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"sparameswaran/nsx-t-gen\",\n\"issueId\": 9\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/sparameswaran/nsx-t-gen/issues/9#issuecomment-390373044"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 336971339\n}"
}
],
"themeColor": "26292E"
}

**Comment by sparameswaran** [comment]
Fixed code to handle empty payloads for lbr, nat rules, ha spoofguard profiles and return.

**Comment by guillierf** [comment]
thanks!
will give a try next week

**Comment by guillierf** [comment]
I commented all the lines under nsx_t_lbr_spec that way:

nsx_t_lbr_spec: |
  loadbalancers:
 `# Sample entry for creating LBR for PAS ERT
 `#- name: PAS-ERT-LBR
 `#  t1_router: T1-MGMT-K8S # Should match a previously declared T1 Router
 `#  size: small                  # Allowed sizes: small, medium, large
 `#  virtual_servers:
 `#  - name: goRouter443          # Unique name that signifies function being exposed
 `#    vip: 10.13.12.150          # Exposed VIP for LBR to listen on
 `#    port: 443
 `#    members:
 `#    - ip: 192.168.24.31        # Internal ip of GoRouter instance 1
 `#      port: 443
 `#    - ip: 192.168.24.32        # Internal ip of GoRouter instance 2
 `#      port: 443
 `#  - name: goRouter80
 `#    vip: 10.13.12.150
 `#    port: 80
 `#    members:
 `#    - ip: 192.168.24.31        # Internal ip of GoRouter instance 1
 `#      port: 80
 `#    - ip: 192.168.24.32        # Internal ip of GoRouter instance 2
 `#      port: 80 
 `#  - name: sshProxy             # SSH Proxy exposed to outside
 `#    vip: 10.13.12.151         
 `#    port: 2222                 # Port 2222 for ssh proxy
 `#    members:
 `#    - ip: 192.168.24.41        # Internal ip of Diego Brain where ssh proxy runs
 `#      port: 2222


but when the pipeline runs, it sends the error output:

Done creating HASwitchingProfiles

Done enabling route redistribution for T0Routers

Adding new Nat rule: {'translated_network': '23.23.23.1', 'rule_priority': 8001, 'enabled': True, 'resource_type': 'NatRule', 'action': 'SNAT', 'match_source_network': '10.1.1.0/24'}
Adding new Nat rule: {'translated_network': '23.23.23.2', 'rule_priority': 8001, 'enabled': True, 'resource_type': 'NatRule', 'action': 'SNAT', 'match_source_network': '10.2.2.0/24'}
Done adding/updating nat rules for T0Routers!!

Traceback (most recent call last):
  File "nsx-t-gen-pipeline/tasks/config-nsx-t-extras/nsx_t_gen.py", line 953, in <module>
    main()
  File "nsx-t-gen-pipeline/tasks/config-nsx-t-extras/nsx_t_gen.py", line 946, in main
    add_loadbalancers()
  File "nsx-t-gen-pipeline/tasks/config-nsx-t-extras/nsx_t_gen.py", line 875, in add_loadbalancers
    if len(lbrs_defn) <= 0:
TypeError: object of type 'NoneType' has no len()

**Comment by sparameswaran** [comment]
Can you remove the `|` also as it makes the yaml think there is content after it.Just set it to:

`nsx_t_lbr_spec:`

Empty line after that. Check what the set-pipeline shows for the variable NSX_T_LBR_SPEC.

**Comment by guillierf** [comment]
just tried.

-param yml file
nsx_t_lbr_spec: 
<END OF FILE>

-fly set-pipeline:
+     NSX_T_LBR_SPEC: null

-run pipeline:
Traceback (most recent call last):
  File "nsx-t-gen-pipeline/tasks/config-nsx-t-extras/nsx_t_gen.py", line 967, in <module>
    main()
  File "nsx-t-gen-pipeline/tasks/config-nsx-t-extras/nsx_t_gen.py", line 960, in main
    add_loadbalancers()
  File "nsx-t-gen-pipeline/tasks/config-nsx-t-extras/nsx_t_gen.py", line 888, in add_loadbalancers
    lbrs_defn = yaml.load(lbr_spec_defn)['loadbalancers']
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by sparameswaran** [comment]
Added changes to handle `null` as a string arg.

**Comment by guillierf** [comment]
yes, it works now

pipeline output:

Done creating HASwitchingProfiles
Done enabling route redistribution for T0Routers
Detected no change with nat rules for T0Routers!!
No yaml payload set for the NSX_T_LBR_SPEC, ignoring loadbalancer section!
NSX Mgr updated to use newly generated CSR!!
    Update response code:202

**Comment by sparameswaran** [comment]
fixed
